Lab 2 - Dart
marynakukhta/metaprog pull request #1
Opened 2020-12-07 00:35 UTC by marynakukhta

@hoherchak 
# Lab 2 - Dart

2020-12-07 07:59 UTC, hoherchak requested changes
При встановленні утиліти через pip має з'являтися окрема команда, а не здійснюватися запуск через python.
Навіть у вашому прикладі не всі класи стають UpperCamelCase, перевірте і виправте.
Зробіть більш тонке перетворення імен в ситуаціях коли всі літери назви у верхньому регістрі.
Не бачу виправлення імен змінних та функцій/методів. Аналогічно для неправильних форматів назв каталогів.
Ви повинні додавати placeholder для документуючого коментаря до всіх класів, методів/функцій.
Також зробіть утиліту in-place, щоб можна було перевірити роботу на бібліотеці.
Звертаю вашу увагу на те, що ваш варіант вже не передбачає здачі на мінімальні 7 балів через штрафні бали, тому вам потрібно буде допрацювати вашу утиліту. Пропоноване покращення наступне: зробіть іменування констант у вигляді `UPPER_SNAKE_CASE`.
Чекаю на виправлення впродовж дня. Поки для допуску на захист недостатньо.

2020-12-07 15:37 UTC, marynakukhta commented
Доброго вечора.
Підкажіть, будь-ласка, що мається на увазі під: "більш тонке перетворення".
Щодо покращення,  вже реалізований метод verify_constant_identifier_names
та fix_constant_identifier_names (PREFER using lowerCamelCase for constant
names instead UPPER_SNAKE_CASE).
constant_identifier_names

пн, 7 дек. 2020 г. в 10:00, Hryhorii Hoherchak <notifications@github.com>:

> *@hoherchak* requested changes on this pull request.
>
> При встановленні утиліти через pip має з'являтися окрема команда, а не
> здійснюватися запуск через python.
> Навіть у вашому прикладі не всі класи стають UpperCamelCase, перевірте і
> виправте.
> Зробіть більш тонке перетворення імен в ситуаціях коли всі літери назви у
> верхньому регістрі.
> Не бачу виправлення імен змінних та функцій/методів. Аналогічно для
> неправильних форматів назв каталогів.
> Ви повинні додавати placeholder для документуючого коментаря до всіх
> класів, методів/функцій.
> Також зробіть утиліту in-place, щоб можна було перевірити роботу на
> бібліотеці.
> Звертаю вашу увагу на те, що ваш варіант вже не передбачає здачі на
> мінімальні 7 балів через штрафні бали, тому вам потрібно буде допрацювати
> вашу утиліту. Пропоноване покращення наступне: зробіть іменування констант
> у вигляді UPPER_SNAKE_CASE.
> Чекаю на виправлення впродовж дня. Поки для допуску на захист недостатньо.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/marynakukhta/metaprog/pull/1#pullrequestreview-545902078>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKJ5PG44F34Y2K3XBZ34XU3STSDQXANCNFSM4UPXAKJA>
> .
>

2020-12-07 15:47 UTC, hoherchak commented
@marynakukhta наприклад `ABC -> abc`, `HELLO_WORLD -> helloWorld` і так далі.
Покращення на те і покращення, що на додатковий бал який вам потрібен треба зробити щось поза умовою лабораторної. Ваш метод робить їх `lowerCamelCase`, зробіть аби було `UPPER_SNAKE_CASE`.

2020-12-07 15:52 UTC, marynakukhta commented
Дякую, зрозуміла.

пн, 7 дек. 2020 г. в 17:48, Hryhorii Hoherchak <notifications@github.com>:

> @marynakukhta <https://github.com/marynakukhta> наприклад ABC -> abc, HELLO_WORLD
> -> helloWorld і так далі.
> Покращення на те і покращення, що на додатковий бал який вам потрібен
> треба зробити щось поза умовою лабораторної. Ваш метод робить їх
> lowerCamelCase, зробіть аби було UPPER_SNAKE_CASE.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/marynakukhta/metaprog/pull/1#issuecomment-740001797>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKJ5PG3LUIDYJTCLD23YIKTSTT2LNANCNFSM4UPXAKJA>
> .
>

2020-12-07 18:08 UTC, closed without merging

2020-12-08 19:17 UTC, hoherchak commented
@marynakukhta Бачу тільки зміну іменування констант, і то не в усіх випадках.

Ось приклад:
```
// Copyright 2018 The Flutter Architecture Sample Authors. All rights reserved. Longer
// Use of this source code is governed by the MIT license that can be found
// in the LICENSE file.
import 'dart:async';
class slider Menu {

import 'package:cloud_firestore/cloud_firestore.dart' as MoJo;
import 'package:todos_repository_core/todos_repository_core.dart';
import 'odos_repository_core/todos_repository_core.dart';

class _totot_bloat {}
class otot_bloat {}
extension _clost<Nana> on

const TreatMeWell = 1
const _treat_me_bad = false
const APP = false

class FirestoreReactive_todosRepository implements ReactiveTodosRepository {
  static const String path = 'todo';

  final Firestore firestore;


  const FirestoreReactive_todosRepository(this.firestore);

  @override
  Future_A<void> add_NewTodo(TodoEntity todo) {
     if (true || !isWeekDay.isEmpty && bla)
       'picture' +
        'juice'

       'theme ' + name + '.'
       var name = null;
    return firestore.collection(path).document(todo.id).setData(todo.toJson());
  }

  @override
  Future_A<void> deleteTodo(List<String> idList) async {
    await Future_A.wait<void>(idList.map((id) {
      return firestore.collection(path).document(id).delete();
    }));
  }

  @override
  Stream<List<TodoEntity>> todos() {
    var localFunction \n = () {
    return firestore.collection(path).snapshots().map((snapshot) {
      return snapshot.documents.map((Doc_B) {
        return TodoEntity(
          Doc_B['task'],
          Doc_B.documentID,
          Doc_B['note'] ?? '',
          Doc_B['complete'] ?? false,
        );
      }).toList();
    });
  }

  @override
  Future_A<void> updateTodo(TodoEntity todo) {
    print('returning store')
    return firestore
        .collection(path)
        .document(todo.id)
        .updateData(todo.toJson());
  }
}
```

Ось результат:
```
// Copyright 2018 The Flutter Architecture Sample Authors. All rights reserved. Longer
// Use of this source code is governed by the MIT license that can be found
// in the LICENSE file.
import 'dart:async';
class slider Menu {

import 'package:cloud_firestore/cloud_firestore.dart' as _Mo_Jo;
import 'package:todos_repository_core/todos_repository_core.dart';
import 'odos_repository_core/todos_repository_core.dart';

class _Totot_Bloat {}
class Otot_Bloat {}
extension _Clost<Nana> on

const TREAT_ME_WELL = 1
const _TREAT_ME_BAD = false
const A_P_P = false

class FirestoreReactive_todosRepository implements ReactiveTodosRepository {
  static const String path = 'todo';

  final Firestore firestore;


  const FirestoreReactive_todosRepository(this.firestore);

  @override
  Future_A<void> add_NewTodo(TodoEntity todo) {
     if (true || !isWeekDay.isEmpty && bla)
       'picture' +
        'juice'

       'theme ' + name + '.'
       var name = null;
    return firestore.collection(path).document(todo.id).setData(todo.toJson());
  }

  @override
  Future_A<void> deleteTodo(List<String> idList) async {
    await Future_A.wait<void>(idList.map((id) {
      return firestore.collection(path).document(id).delete();
    }));
  }

  @override
  Stream<List<TodoEntity>> todos() {
    var localFunction \n = () {
    return firestore.collection(path).snapshots().map((snapshot) {
      return snapshot.documents.map((Doc_B) {
        return TodoEntity(
          Doc_B['task'],
          Doc_B.documentID,
          Doc_B['note'] ?? '',
          Doc_B['complete'] ?? false,
        );
      }).toList();
    });
  }

  @override
  Future_A<void> updateTodo(TodoEntity todo) {
    print('returning store')
    return firestore
        .collection(path)
        .document(todo.id)
        .updateData(todo.toJson());
  }
}
```
Повноцінної коректної заміни немає для жодного елементу. Окремої команди (не через python) теж немає.
Перевірки документації немає. Утиліта створює нові файли замість того, щоб змінювати існуючий.
Поки можу додати хіба один бал.